### ISSUE TITLE
Install under Pop!OS 20.10 wont start

### ISSUE THREAD

**Issue by tbrumm** [KrispyCamel4u/SysMonTask#1]
Hey, it will not start under Pop!IOS 20.10, here the output from terminal:

sysmontask 
/usr/lib/python3/dist-packages/sysmontask/sysmontask.py:5: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as g , GLib as go
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 27, in <module>
    from mem import *
ModuleNotFoundError: No module named 'mem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask==1.0.0', 'console_scripts', 'sysmontask')())
  File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 36, in <module>
    from sysmontask.sidepane import *
  File "/usr/lib/python3/dist-packages/sysmontask/sidepane.py", line 5, in <module>
    from gi_composites import GtkTemplate
ModuleNotFoundError: No module named 'gi_composites'

**Comment by KrispyCamel4u** [comment]
Hi,
Thank you for reporting the bug.
You currently doesn't have a module needed.
For installing, run:
```
$ pip3 install pygi-composite-templates
```
After that it will work. I have tried implimenting it in the dependencies to install automatically looks like it need attention.
I will try to make it better. Please update me if the problem still persists.

Thank you
