### ISSUE TITLE
Build fails on Manjaro Linux

### ISSUE THREAD

**Issue by gimmebackmysandwich** [KrispyCamel4u/SysMonTask#104]
Using Add/Remove Software and enabling AUR repository to build the app. Doing so returns the following error:

`Preparing...
Checking sysmontask dependencies...
Resolving dependencies...
Checking inter-conflicts...
Download of m4 (1.4.19-1) started
Download of m4 (1.4.19-1) finished
Download of pkgconf (1.8.0-1) started
Download of pkgconf (1.8.0-1) finished
Download of gc (8.2.0-2) started
Download of gc (8.2.0-2) finished
Download of autoconf (2.71-1) started
Download of autoconf (2.71-1) finished
Download of bison (3.8.2-1) started
Download of bison (3.8.2-1) finished
Download of patch (2.7.6-8) started
Download of patch (2.7.6-8) finished
Download of guile (2.2.7-2) started
Download of guile (2.2.7-2) finished
Download of make (4.3-3) started
Download of make (4.3-3) finished
Download of automake (1.16.5-1) started
Download of flex (2.6.4-3) started
Download of automake (1.16.5-1) finished
Download of flex (2.6.4-3) finished
Checking keyring...
Checking integrity...
Loading packages files...
Checking file conflicts...
Checking available disk space...
Installing m4 (1.4.19-1)...
Installing flex (2.6.4-3)...
Installing pkgconf (1.8.0-1)...
Installing gc (8.2.0-2)...
Installing autoconf (2.71-1)...
Installing guile (2.2.7-2)...
Installing bison (3.8.2-1)...
Installing patch (2.7.6-8)...
Installing make (4.3-3)...
Installing automake (1.16.5-1)...
Running post-transaction hooks...
Arming ConditionNeedsUpdate...
Updating the info directory file...
Cloning sysmontask build files...
Generating sysmontask information...

Building sysmontask...
==> Making package: sysmontask 1:1.x.x-2 (Wed 16 Feb 2022 01:04:46 AM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading sysmontask-1.x.x.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
100   105  100   105    0     0     16      0  0:00:06  0:00:06 --:--:--    26
  -> Found sysmontask.patch
  -> Found sysmontask-pkexec
  -> Found org.freedesktop.sysmontask.policy
==> Validating source files with sha256sums...
    sysmontask-1.x.x.tar.gz ... FAILED
    sysmontask.patch ... Passed
    sysmontask-pkexec ... Passed
    org.freedesktop.sysmontask.policy ... Passed
==> ERROR: One or more files did not pass the validity check!
Failed to build sysmontask`

OS version: Manjaro XFCE 21.2.2

**Comment by yochananmarqos** [comment]
The 1.x.x tag was removed, it's fixed with 1:1.x.x-3.

@KrispyCamel4u FYI:

```
/usr/lib/python3.10/site-packages/setuptools/dist.py:501: UserWarning: The version specified ('1.x.x') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```

**Comment by major-mayer** [comment]
> The 1.x.x tag was removed, it's fixed with 1:1.x.x-3.

I tried installing 1:1.x.x-6 and it still returns 
```
/usr/lib/python3.10/site-packages/setuptools/_normalization.py:93: SetuptoolsDeprecationWarning: Invalid version: '1.x.x'.
        !!


        ###################
        # Invalid version #
        ###################
        '1.x.x' is not valid according to PEP 440.

        Please make sure specify a valid version for your package.
        Also note that future releases of setuptools may halt the build process
        if an invalid version is given.
        

!!
        
  warnings.warn(cleandoc(msg), SetuptoolsDeprecationWarning)
Traceback (most recent call last):
  File "/var/tmp/pamac-build-laurenz/sysmontask/src/SysMonTask/setup.py", line 19, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 63, in run
    self.build_package_data()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 159, in build_package_data
    for target, srcfile in self._get_package_data_output_mapping():
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 151, in _get_package_data_output_mapping
    for package, src_dir, build_dir, filenames in self.data_files:
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 72, in __getattr__
    self.data_files = self._get_data_files()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 84, in _get_data_files
    self.analyze_manifest()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 181, in analyze_manifest
    self.run_command('egg_info')
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 220, in finalize_options
    parsed_version = packaging.version.Version(self.egg_version)
  File "/usr/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '1.x.x'
``` 

Am I doing something wrong?

**Comment by yochananmarqos** [comment]
@major-mayer No, it's due to changes with Setuptools. I've implemented a workaround with [1:1.3.9+16+g7c96959-1](https://aur.archlinux.org/cgit/aur.git/commit/?h=sysmontask&id=fa18bc46321c0267e63430f48a933b260570e21f).

**Comment by major-mayer** [comment]
Okay thanks for the hint. I will try out the git version for now.

**Comment by yochananmarqos** [comment]
@major-mayer What git version? I'm talking about the `sysmontask` AUR package. Notice I linked the commit in my reply. 😉

**Comment by major-mayer** [comment]
Oh sorry, I got confused.
I thought there would be another sysmontask-git version of this package in the AUR, but this isn't the case.
But with the new update of your AUR package, everything is working again, so I think you can close this issue :slightly_smiling_face:
