### ISSUE TITLE
crash on launch when trying to access '/var/lib/docker/btrfs'

### ISSUE THREAD

**Issue by GithubUser5462** [KrispyCamel4u/SysMonTask#108]
Installed on arch using yay,  `sysmontask` crashes on launch with the following output:
```
$ sysmontask                        
5.9.0

(sysmontask:27822): Wnck-WARNING **: 18:25:54.530: libwnck is designed to work in X11 only, no valid display found
color prifile in the setting {'cpu': (0.384, 0.749, 1.0), 'memory': (0.627, 0.196, 0.788), 'disk': (0.109, 0.67, 0.0588), 'network': (0.709, 0.164, 0.164), 'gpu': (0.384, 0.749, 1.0)}
cpuInit
Memory Tab Initialising
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
Failed to get Memory Form Factor
nvme0n1
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask===1.x.x', 'console_scripts', 'sysmontask')())
  File "/usr/lib/python3.10/site-packages/sysmontask/sysmontask.py", line 1127, in start
    main=myclass()
  File "/usr/lib/python3.10/site-packages/sysmontask/sysmontask.py", line 187, in __init__
    self.diskinitialisation()
  File "/usr/lib/python3.10/site-packages/sysmontask/disk.py", line 334, in diskinit
    temp=ps.disk_usage(part[1])
  File "/usr/lib/python3.10/site-packages/psutil/__init__.py", line 2003, in disk_usage
    return _psplatform.disk_usage(path)
  File "/usr/lib/python3.10/site-packages/psutil/_psposix.py", line 170, in disk_usage
    st = os.statvfs(path)
PermissionError: [Errno 13] Permission denied: '/var/lib/docker/btrfs'
```

`sysmontask-pkexec` works, but it doesn't follow the color sheme, asks for the password and shows the changelog on every launch.

**Comment by rodrigopedra** [comment]
If you have docker installed, try stopping docker service. 

In the distro I use (openSUSE TW) the command is this one:

~~~
systemctl stop docker.service
~~~

I think it might work regardless of docker, but this is a workaround
