### ISSUE TITLE
Can't start sysmontask (kubuntu 22.04)

### ISSUE THREAD

**Issue by poopman97** [KrispyCamel4u/SysMonTask#115]
I've just upgraded form 21.10 to 22.04 and when I try to start sysmontask I get this error

`vidak@vidakov-super-komp:~$ sysmontask
Traceback (most recent call last):
  File "/usr/local/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask===1.x.x', 'console_scripts', 'sysmontask')())
  File "/usr/local/bin/sysmontask", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for sysmontask`

**Comment by IPockAUsername** [comment]
Same issue! How did you solve it?
