### ISSUE TITLE
gi.repository.Gtk' object has no attribute 'Container'

### ISSUE THREAD

**Issue by alcir** [KrispyCamel4u/SysMonTask#12]
Trying to use sysmontask on Fedora 34 (on F33 python3-psutil is still at version 5.7.2)
Running sysmontask I get:

```text
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask==1.1.0', 'console_scripts', 'sysmontask')())
  File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 5, in <module>
    from gi.repository import Gtk as g , GLib as go
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/usr/lib64/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 168, in <module>
    class Container(Gtk.Container, Widget):
  File "/usr/lib64/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Container'
```

What could it be?

**Comment by KrispyCamel4u** [comment]
Hi,
I am assuming you are trying to run from the source(if that is not the case then please let me know the details). I have tried running the source code on fedora33-workstation-gnome-Wayland. I didn't face any issues as such.

I see that the version that you are using is 1.1.0 which has some serious bugs. So, try using the newest one. 

If that is not the case then:
since it requires psutil>=5.7.3 and the newest will be better, try upgrading/installing the psutil using "sudo pip3 install -U psutil" (system-wide). 

If still the issue persists then please let me know.

**Comment by alcir** [comment]
Thank you for the answer.
Actually I was using the sources downloaded from https://github.com/KrispyCamel4u/SysMonTask/releases/tag/v1.1.1_beta

**Comment by KrispyCamel4u** [comment]
> Thank you for the answer.
> Actually I was using the sources downloaded from https://github.com/KrispyCamel4u/SysMonTask/releases/tag/v1.1.1_beta
Thanks now I have updated the source in the release too.

**Comment by alcir** [comment]
Mmm. Mybe I'm wrong or there is some cache in the middle, but tar.gz and zip files still contains 1.1.0

**Comment by KrispyCamel4u** [comment]
> Mmm. Mybe I'm wrong or there is some cache in the middle, but tar.gz and zip files still contains 1.1.0

Hmm I checked it, looked like I did not change the tag settings that why the compressed files didn't change. Now its is done and the compressed files shows correctly.

**Comment by alcir** [comment]
Thanks.
Ok. Now the window asking for the password appears, but there are the same error messages.

```text
acquired root permission
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask==1.1.1', 'console_scripts', 'sysmontask')())
  File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 12, in <module>
    from gi.repository import Gtk as g , GLib as go
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/usr/lib64/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 168, in <module>
    class Container(Gtk.Container, Widget):
  File "/usr/lib64/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Container'
```

(Background: I was looking to create an rpm for Fedora 34)

**Comment by KrispyCamel4u** [comment]
> Thanks.
> Ok. Now the window asking for the password appears, but there are the same error messages.
> 
> ```
> acquired root permission
> Traceback (most recent call last):
>   File "/usr/bin/sysmontask", line 33, in <module>
>     sys.exit(load_entry_point('sysmontask==1.1.1', 'console_scripts', 'sysmontask')())
>   File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 12, in <module>
>     from gi.repository import Gtk as g , GLib as go
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
>   File "/usr/lib64/python3.9/site-packages/gi/importer.py", line 145, in load_module
>     dynamic_module = load_overrides(introspection_module)
>   File "/usr/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
>     override_mod = importlib.import_module(override_package_name)
>   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 168, in <module>
>     class Container(Gtk.Container, Widget):
>   File "/usr/lib64/python3.9/site-packages/gi/module.py", line 123, in __getattr__
>     raise AttributeError("%r object has no attribute %r" % (
> AttributeError: 'gi.repository.Gtk' object has no attribute 'Container'
> ```
> 
> (Background: I was looking to create an rpm for Fedora 34)

did you try upgrading/reinsalling psutil?

**Comment by alcir** [comment]
python3-psutil is at 5.8.0 version

**Comment by KrispyCamel4u** [comment]
hi
This problem tends to be associated with the PyGObject(Gtk) module. But since this worked on fedora 33 on the virtual machine. This might be due to some version mismatch(or something else) on fedora 34. Can you try uncommenting the line 2,3 of /sysmontask/sysmontask.py
from
```
# import gi
# gi.require_version("Gtk", "3.")
```
modifying to 
```
import gi
gi.require_version("Gtk", "3.0")
```
I am not sure whether this will solve it or not but it is worth a try.
Please let me know the details.

**Comment by sowrensen** [comment]
> hi
> This problem tends to be associated with the PyGObject(Gtk) module. But since this worked on fedora 33 on the virtual machine. This might be due to some version mismatch(or something else) on fedora 34. Can you try uncommenting the line 2,3 of /sysmontask/sysmontask.py
> from
> 
> ```
> # import gi
> # gi.require_version("Gtk", "3.")
> ```
> 
> modifying to
> 
> ```
> import gi
> gi.require_version("Gtk", "3.0")
> ```
> 
> I am not sure whether this will solve it or not but it is worth a try.
> Please let me know the details.

Yes, it worked. I encountered the same issue on Manjaro 20.2.1 Gnome. And I get it running by following this.

**Comment by alcir** [comment]
Yes. It works. :+1:

**Comment by KrispyCamel4u** [comment]
Hi,
The new version is out, the issue has been fixed. Please update me from your side.
