### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'N/'

### ISSUE THREAD

**Issue by mpilka** [KrispyCamel4u/SysMonTask#13]
* Ubuntu 20.04.1 LTS
*  SysMonTask_1.1.1_beta

```
sudo sysmontask
...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 465, in updater
    self.gpuTabUpdate()
  File "/usr/lib/python3/dist-packages/sysmontask/gpu.py", line 369, in gpuUpdate
    self.gpuEncodingArray.append(int(gpuinfoRoot.find('gpu').find('utilization').find('encoder_util').text[:-1]))
ValueError: invalid literal for int() with base 10: 'N/'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sysmontask/gpu.py", line 179, in gpuencodingdrawarea_draw
    cr.line_to((i+1)*stepsize,scalingfactor*(100-self.gpuencodingArray[i+1]))
IndexError: list index out of range
```

**Comment by KrispyCamel4u** [comment]
Hi,
Thanks for reporting. 
Can you share the output of the below command with me. 
```
$ nvidia-smi -q -x    
```
It will help me to fix it better. Please let me know if you can do this.

**Comment by KrispyCamel4u** [comment]
Hey,
I have fixed the issue with a new release. Let me know about it after updating.
