### ISSUE TITLE
Doesnt Seem To Work With Gruvbox-dark-gtk

### ISSUE THREAD

**Issue by stnm12brX2** [KrispyCamel4u/SysMonTask#28]
https://github.com/jmattheis/gruvbox-dark-gtk
I am using arch with i3 installed, i used the command given and received this
` sudo sysmontask.set_dark
[sudo] password for USER: 
0 : gruvbox-dark-gtk
Index for Corresponding Theme that you want to apply?:0
Failed to set Theme:( 
Run with sudo(root privileges) is required.
`
I then used lxaqppearance to set gruvbox-dark-gtk as my them of choice and the bubble asking me for my password appeared to change to the gruvbox theme. After I hit enter the bubble disappears and sysmontask doesn't start. I used htop and it wasn't even running. IDK what files I should include, please LMK. Thank you!

**Comment by stnm12brX2** [comment]
edit was to try to separate the lines of the console output, but IDK how

**Comment by stnm12brX2** [comment]
sure:
sysmontask
[sudo] password for USER: acquired root permission
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask==1.1.1', 'console_scripts', 'sysmontask')())
  File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 12, in <module>
    from gi.repository import Gtk as g , GLib as go
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/usr/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 168, in <module>
    class Container(Gtk.Container, Widget):
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Container'

**Comment by KrispyCamel4u** [comment]
You can try changing in one file if you want:
Goto "/usr/lib/python3.9/site-packages/sysmontask/" this location and follow the steps mentioned at last here
[https://github.com/KrispyCamel4u/SysMonTask/issues/12]()
That should solve the issue. In any case please update me.

**Comment by KrispyCamel4u** [comment]
Hi,
Can you update me about the issue?

**Comment by stnm12brX2** [comment]
Now, after I made that change it didn't even prompt me to input my password. I have since uninstalled and reinstalled it and it prompts me for my password again. It still gives me the first error without starting.

**Comment by KrispyCamel4u** [comment]
> I was busy sorry:
> sudo sysmontask
> Traceback (most recent call last):
> File "/usr/bin/sysmontask", line 33, in
> sys.exit(load_entry_point('sysmontask==1.1.1', 'console_scripts', 'sysmontask')())
> File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
> return next(matches).load()
> File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
> module = import_module(match.group('module'))
> File "/usr/lib/python3.9/importlib/**init**.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1030, in _gcd_import
> File "", line 1007, in _find_and_load
> File "", line 986, in _find_and_load_unlocked
> File "", line 680, in _load_unlocked
> File "", line 790, in exec_module
> File "", line 228, in _call_with_frames_removed
> File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 3, in
> gi.require_version("Gtk", "3.")
> File "/usr/lib/python3.9/site-packages/gi/**init**.py", line 129, in require_version
> raise ValueError('Namespace %s not available for version %s' %
> ValueError: Namespace Gtk not available for version 3.

Hi looks like you missed one thing: 
```
import gi
gi.require_version("Gtk", "3.0")
```
Actually you are supposed to put '0' after '3.' in line number 3 of sysmontask.py  after uncommenting it like given up here and probably you won't get this error anymore. let me know the details in any case.

**Comment by stnm12brX2** [comment]
It now runs correctly, but it is in light mode. I ran the same command as my first comment and it still gives me the run with sudo error, even though I ran it as sudo.

**Comment by stnm12brX2** [comment]
I restarted and now it's giving me this error.......
❯ sysmontask
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask===1.1.1-beta-b', 'console_scripts', 'sysmontask')())
  File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 71, in <module>
    session_index=session_finder()
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 47, in session_finder
    sess=os.environ.get("DESKTOP_SESSION").lower()
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by KrispyCamel4u** [comment]
Ok, I will fix it in the next release in few days. 
For the quick fix:
Replace the content for the sysmontask.py file in the installation directory(/usr/lib/python3/dist-packages/sysmontask/sysmontask.py) to the content of the file attached or replace the file after renaming the attached file to "sysmontask.py". It will fix the issue and hopefully will work with no more issues. In any case, let me know.

[sysmontask.txt](https://github.com/KrispyCamel4u/SysMonTask/files/6127393/sysmontask.txt)

**Comment by stnm12brX2** [comment]
Sorry for the late response, it works 100% correctly, thank you!

**Comment by KrispyCamel4u** [comment]
Hi,
A new version is out and this issue has been fixed and some overall modifications and new features have been added, check out readme to know more.
Let me know if you still face this issue or not in the new release.
