### ISSUE TITLE
Not working in FerenOS

### ISSUE THREAD

**Issue by achede22** [KrispyCamel4u/SysMonTask#29]
achede@achede-foxconn:~$ sysmontask
acquired root permission
/usr/lib/python3/dist-packages/sysmontask/sysmontask.py:12: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as g , GLib as go
/usr/lib/python3/dist-packages/sysmontask/proc.py:1: PyGIWarning: Wnck was imported without specifying a version first. Use gi.require_version('Wnck', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as g , GLib as go,GdkPixbuf,Wnck, Gio

(sysmontask:27563): Gtk-WARNING **: 15:18:51.464: Could not load image 'usr/share/sysmontask/icons/SysMonTask.png': Failed to open file “/usr/share/sysmontask/glade_files/usr/share/sysmontask/icons/SysMonTask.png”: No such file or directory
memory tab initialising
fd0
sda
sdb
sdc
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 11, in <module>
    load_entry_point('sysmontask==1.1.1', 'console_scripts', 'sysmontask')()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 842, in start
    main=myclass()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 84, in __init__
    self.diskinitialisation()
  File "/usr/lib/python3/dist-packages/sysmontask/disk.py", line 267, in diskinit
    disktemp=ps.disk_io_counters(perdisk=True)
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 2131, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1121, in disk_io_counters
    for entry in gen:
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1094, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   7       0 loop0 55 0 2142 2159 0 0 0 0 0 1368 2159 0 0 0 0 0 0\n'
achede@achede-foxconn:~$

**Comment by KrispyCamel4u** [comment]
Hi
This happens because the psutil is not at the required version. Read more in readme about it
.

**Comment by KrispyCamel4u** [comment]
Hi,
Can you update me about the issue?
