### ISSUE TITLE
Not working on Linux Lite (Ubuntu 20.04.2)

### ISSUE THREAD

**Issue by HackMan37** [KrispyCamel4u/SysMonTask#31]
Hi, i install the program well, no problem, and update the psutil too with the command that you give on the Readme. but i have problem opening the program, the log is:

acquired root permission
/usr/lib/python3/dist-packages/sysmontask/sysmontask.py:12: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as g , GLib as go
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 27, in <module>
    from sidepane import *
ModuleNotFoundError: No module named 'sidepane'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask==1.1.1', 'console_scripts', 'sysmontask')())
  File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 37, in <module>
    from sysmontask.disk import *
  File "/usr/lib/python3/dist-packages/sysmontask/disk.py", line 17, in <module>
    from sysmontask.proc import sorting_func,byte_to_human
  File "/usr/lib/python3/dist-packages/sysmontask/proc.py", line 1, in <module>
    from gi.repository import Gtk as g , GLib as go,GdkPixbuf,Wnck, Gio
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 132, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Wnck, introspection typelib not found

**Comment by KrispyCamel4u** [comment]
Hi,
Thanks for it.
Unfortunately, it depends on one more package which in general is pre-installed but not for all. 
You can install the package by running:
```
$ sudo apt install gir1.2-wnck-3.0
```
I will also add this in dependencies so that it gets installed automatically if not installed.
Please update me if it get solved or not.

**Comment by HackMan37** [comment]
It work!!!!!
A lot of thanks bro :3

**Comment by KrispyCamel4u** [comment]
I have added this in dependencies.
