### ISSUE TITLE
can't running apps

### ISSUE THREAD

**Issue by ahsandev2019** [KrispyCamel4u/SysMonTask#41]
i got error like this when i run sudo sysmontask
this is my os 
OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 5.4.0-52-generic
Shell: zsh 5.4.2

(sysmontask:5418): Gtk-WARNING **: 12:23:18.674: Theme parsing error: gtk.css:6777:29: Missing opening bracket in color definition

(sysmontask:5418): Gtk-WARNING **: 12:23:18.674: Theme parsing error: gtk.css:6779:34: Missing opening bracket in color definition

(sysmontask:5418): Gtk-WARNING **: 12:23:18.674: Theme parsing error: gtk.css:6785:28: Missing opening bracket in color definition
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 11, in <module>
    load_entry_point('sysmontask===1.1.1-beta-b', 'console_scripts', 'sysmontask')()
  File "/home/ahsan/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ahsan/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/home/ahsan/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/home/ahsan/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 71, in <module>
    session_index=session_finder()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 47, in session_finder
    sess=os.environ.get("DESKTOP_SESSION").lower()
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by KrispyCamel4u** [comment]
Hi, 
Thanks for it,
For the quick fix look at the last of this thread [https://github.com/KrispyCamel4u/SysMonTask/issues/28](issue 28)
I will fix this in an upcoming release. For please use the fix.

**Comment by KrispyCamel4u** [comment]
Hi,
You can update me if it still persists or it is solved?

**Comment by ahsandev2019** [comment]
thanks everything working now :)
