### ISSUE TITLE
Not Working on Arch Linux

### ISSUE THREAD

**Issue by akacdrom** [KrispyCamel4u/SysMonTask#45]
When I try to run it.

`Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask===1.1.1-beta-b', 'console_scripts', 'sysmontask')())
  File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 71, in <module>
    session_index=session_finder()
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 62, in session_finder
    sess=os.environ.get("XDG_CURRENT_DESKTOP").lower()
AttributeError: 'NoneType' object has no attribute 'lower'`

**Comment by KrispyCamel4u** [comment]
hi,
For the quick fix you can follow the last steps in the discussion here.
issue #28

**Comment by KrispyCamel4u** [comment]
Hi,
A new release has been published and this issue has been fixed with a couple of other useful features check out readme to know more.
Let me know if you still face this issue or not.

**Comment by KrispyCamel4u** [comment]
I am closing this issue now, in case you face an issue, you can open it again.
