### ISSUE TITLE
unknown signal name: clicked

### ISSUE THREAD

**Issue by yochananmarqos** [KrispyCamel4u/SysMonTask#47]
SysMonTask 1.3.7 (AUR)
Manjaro GNOME (Xorg)

```
❯ sysmontask
5.8.0
cpuInit
memory tab initialising
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
Failed to get Memory Form Factor
sda
nvme1n1
nvme0n1
okk
save button
update Dir right True
update speed to normal
initialisating sidepane
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask==1.3.7', 'console_scripts', 'sysmontask')())
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 796, in start
    main=myclass()
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 191, in __init__
    self.sidepaneinitialisation()
  File "/usr/lib/python3.9/site-packages/sysmontask/sidepane.py", line 343, in sidepaneinit
    self.gpuSidePaneWidget.connect('clicked',on_switcher_clicked,self.performanceStack,self.current_stack)
TypeError: <sidepane.gpuSidepaneWidget object at 0x7f5004325640 (gpuSidepaneWidget at 0x55afe30fef30)>: unknown signal name: clicked
```

```
❯ sudo sysmontask
5.8.0
cpuInit
memory tab initialising
sda
nvme1n1
nvme0n1
okk
save button

(sysmontask:184071): dconf-WARNING **: 08:38:18.863: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=7a2551911753462a8e997be0eab9c8f6 --binary-syntax --close-stderr”: Child process exited with code 1
update Dir right True
update speed to normal
initialisating sidepane
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask==1.3.7', 'console_scripts', 'sysmontask')())
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 796, in start
    main=myclass()
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 191, in __init__
    self.sidepaneinitialisation()
  File "/usr/lib/python3.9/site-packages/sysmontask/sidepane.py", line 343, in sidepaneinit
    self.gpuSidePaneWidget.connect('clicked',on_switcher_clicked,self.performanceStack,self.current_stack)
TypeError: <sidepane.gpuSidepaneWidget object at 0x7ff2dc301940 (gpuSidepaneWidget at 0x558ba3beaf50)>: unknown signal name: clicked
```

**Comment by KrispyCamel4u** [comment]
Hi 
Thank you for this. I have got the problem and I will publish a new patch.

**Comment by KrispyCamel4u** [comment]
Hi,
I have made changes in the source to fix the bug :)

**Comment by yochananmarqos** [comment]
Thanks, 1.3.9 works. FYI, the About dialog still says 1.3.7.

**Comment by KrispyCamel4u** [comment]
> Thanks, 1.3.9 works. FYI, the About dialog still says 1.3.7.

Thanks
I will change it while fixing new bugs.
