### ISSUE TITLE
Error trying to open sysmontask

### ISSUE THREAD

**Issue by Jonesyj83** [KrispyCamel4u/SysMonTask#63]
Have install as the instructions have said but get this error when I try to run sysmontask

`5.8.0
cpuInit
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 11, in <module>
    load_entry_point('sysmontask==1.3.9', 'console_scripts', 'sysmontask')()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 796, in start
    main=myclass()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 130, in __init__
    self.cpuInit()
  File "/usr/lib/python3/dist-packages/sysmontask/cpu.py", line 129, in cpuInit
    if column < self.num_of_column_per_row[self.cpu_logical_cores]:
KeyError: 40
`

**Comment by KrispyCamel4u** [comment]
> 
> 
> Have install as the instructions have said but get this error when I try to run sysmontask
> 
> `5.8.0 cpuInit Traceback (most recent call last): File "/usr/bin/sysmontask", line 11, in <module> load_entry_point('sysmontask==1.3.9', 'console_scripts', 'sysmontask')() File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 796, in start main=myclass() File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 130, in __init__ self.cpuInit() File "/usr/lib/python3/dist-packages/sysmontask/cpu.py", line 129, in cpuInit if column < self.num_of_column_per_row[self.cpu_logical_cores]: KeyError: 40 `

hi, thanks
Can you specify the the cpu and number of cores it has?

**Comment by Jonesyj83** [comment]
it's dual Intel Xeon e5-2680 v2 and has 10 cores each

**Comment by KrispyCamel4u** [comment]
Thanks, I will fix it soon.

**Comment by GrzegorzWRO** [comment]
> Thanks, I will fix it soon.

Hi, I have something similar 


> 5.8.0
cpuInit
Failed to get Cache information
Traceback (most recent call last):
  File "/bin/sysmontask", line 11, in <module>
    load_entry_point('sysmontask==1.3.9', 'console_scripts', 'sysmontask')()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 796, in start
    main=myclass()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 130, in __init__
    self.cpuInit()
  File "/usr/lib/python3/dist-packages/sysmontask/cpu.py", line 129, in cpuInit
    if column < self.num_of_column_per_row[self.cpu_logical_cores]:
KeyError: 36
> 

I have xeon E5-2699V3 18 cores

**Comment by CryptoBlockchainTechnologies** [comment]
```
sysmontask
5.8.0
cpuInit
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 11, in <module>
    load_entry_point('sysmontask==1.3.9', 'console_scripts', 'sysmontask')()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 796, in start
    main=myclass()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 130, in __init__
    self.cpuInit()
  File "/usr/lib/python3/dist-packages/sysmontask/cpu.py", line 129, in cpuInit
    if column < self.num_of_column_per_row[self.cpu_logical_cores]:
KeyError: 72
```
I have 2xE5-2699V3 18cores. So 36 cores, 72 threads. Looks like error is number of threads.

**Comment by KrispyCamel4u** [comment]
Now you can use sysmontask with the new release.
Please verify that it is solved.
