### ISSUE TITLE
Process Menu Need to Refresh Manually and Not Working

### ISSUE THREAD

**Issue by GokhanOfficial** [KrispyCamel4u/SysMonTask#72]
Performance menu is working perfectly but Process menu is not working at all. Not refreshing automatic and monitoring feature not working. CPU, rCPU, DiskRead and DiskWrite are always showing zero. Memory and rMemory are showing zero or a constant value. Also new process isn't listing until manually refreshing or restarting the app.

**My system info:**
```
[code]
System:    Host: <filter> Kernel: 5.10.0-5mx-amd64 x86_64 bits: 64 compiler: N/A 
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.10.0-5mx-amd64 
           root=UUID=<filter> ro quiet splash 
           Desktop: Xfce 4.14.2 tk: Gtk 3.24.5 info: xfce4-panel wm: xfwm4 dm: LightDM 1.26.0 
           Distro: MX-19.4_x64 patito feo March 31  2021 base: Debian GNU/Linux 10 (buster) 
Machine:   Type: Laptop System: ASUSTeK product: X541SA v: 1.0 serial: <filter> 
           Mobo: ASUSTeK model: X541SA v: 1.0 serial: <filter> UEFI: American Megatrends 
           v: X541SA.307 date: 04/19/2019 
Battery:   ID-1: BAT0 charge: 11.4 Wh condition: 27.1/34.6 Wh (78%) volts: 10.8/10.8 
           model: ASUSTeK X550A26 type: Li-ion serial: <filter> status: Discharging cycles: 855 
CPU:       Topology: Dual Core model: Intel Celeron N3060 bits: 64 type: MCP arch: Airmont 
           family: 6 model-id: 4C (76) stepping: 4 microcode: 411 L2 cache: 1024 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 6400 
           Speed: 2443 MHz min/max: 480/2480 MHz Core speeds (MHz): 1: 2443 2: 1043 
           Vulnerabilities: Type: itlb_multihit status: Not affected 
           Type: l1tf status: Not affected 
           Type: mds mitigation: Clear CPU buffers; SMT disabled 
           Type: meltdown mitigation: PTI 
           Type: spec_store_bypass status: Not affected 
           Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization 
           Type: spectre_v2 mitigation: Full generic retpoline, IBPB: conditional, IBRS_FW, 
           STIBP: disabled, RSB filling 
           Type: srbds status: Not affected 
           Type: tsx_async_abort status: Not affected 
Graphics:  Device-1: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated 
           Graphics 
           vendor: ASUSTeK driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:22b1 
           Display: x11 server: X.Org 1.20.4 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 400 (Braswell) v: 4.5 Mesa 18.3.6 
           compat-v: 3.0 direct render: Yes 
Audio:     Device-1: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series High 
           Definition Audio 
           vendor: ASUSTeK driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:2284 
           Sound Server: ALSA v: k5.10.0-5mx-amd64 
Network:   Device-1: Realtek RTL8101/2/6E PCI Express Fast/Gigabit Ethernet 
           vendor: ASUSTeK RTL810xE driver: r8169 v: kernel port: e000 bus ID: 02:00.0 
           chip ID: 10ec:8136 
           IF: eth0 state: down mac: <filter> 
           Device-2: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter 
           vendor: AzureWave driver: ath9k v: kernel port: e000 bus ID: 03:00.0 
           chip ID: 168c:0036 
           IF: wlan0 state: up mac: <filter> 
Drives:    Local Storage: total: 689.33 GiB used: 12.58 GiB (1.8%) 
           ID-1: /dev/sda vendor: Kingston model: SA400S37240G size: 223.57 GiB block size: 
           physical: 512 B logical: 512 B speed: 6.0 Gb/s serial: <filter> rev: B1E1 temp: 31 C 
           scheme: GPT 
           ID-2: /dev/sdb vendor: Toshiba model: MQ01ABF050 size: 465.76 GiB block size: 
           physical: 4096 B logical: 512 B speed: 6.0 Gb/s rotation: 5400 rpm serial: <filter> 
           rev: 3J scheme: GPT 
Partition: ID-1: / raw size: 16.00 GiB size: 15.62 GiB (97.65%) used: 6.16 GiB (39.4%) fs: ext4 
           dev: /dev/sda7 
           ID-2: /home raw size: 10.00 GiB size: 9.78 GiB (97.81%) used: 5.54 GiB (56.7%) 
           fs: ext4 dev: /dev/sda5 
           ID-3: swap-1 size: 4.00 GiB used: 879.5 MiB (21.5%) fs: swap 
           swappiness: 15 (default 60) cache pressure: 100 (default) dev: /dev/sda4 
Sensors:   System Temperatures: cpu: 6280.4 C mobo: 45.0 C 
           Fan Speeds (RPM): cpu: 2300 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/camel-neeraj-ubuntu-sysmontask-impish.list 
           1: deb http://ppa.launchpad.net/camel-neeraj/sysmontask/ubuntu impish main
           Active apt repos in: /etc/apt/sources.list.d/debian-stable-updates.list 
           1: deb http://deb.debian.org/debian buster-updates main contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/debian.list 
           1: deb http://deb.debian.org/debian buster main contrib non-free
           2: deb http://deb.debian.org/debian-security buster/updates main contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/mx.list 
           1: deb http://ftp.linux.org.tr/mx/repo/mx/repo/ buster main non-free
           No active apt repos in: /etc/apt/sources.list.d/various.list 
Info:      Processes: 202 Uptime: 1h 02m Memory: 1.84 GiB used: 1.45 GiB (79.1%) Init: SysVinit 
           v: 2.93 runlevel: 5 default: 5 Compilers: gcc: 8.3.0 alt: 8 Shell: quick-system-in 
           running in: quick-system-in inxi: 3.0.36 
[/code]
```

**Terminal Log:**
```
$ sudo sysmontask
5.8.0
cpuInit
Failed to get Cache information
memory tab initialising
sda
sdb
/bin/sh: 1: nvidia-smi: not found
no nvidia gpu found
save button
update Dir right True
update speed to normal
initialisating sidepane
total window 4.574685573577881
hello
appending 2805
appending 2889
appending 2945
appending 3038
appending 3170
appending 3215
appending 3270
appending 3308
appending 3310
appending 3313
appending 3321
appending 3389
appending 3394
appending 3414
appending 3420
appending 3421
appending 3425
appending 3449
appending 3463
appending 3867
appending 3912
appending 3952
appending 3958
appending 4068
appending 4167
appending 4217
appending 4530
appending 5604
appending 6020
appending 8423
appending 14156
appending 16325
appending 16357
appending 16358
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sysmontask-1.3.9-py3.7.egg/sysmontask/gproc.py", line 693, in procUpdate
    for pidds in reversed_process(tempdi):
  File "/usr/local/lib/python3.7/dist-packages/sysmontask-1.3.9-py3.7.egg/sysmontask/gproc.py", line 29, in reversed_process
    return reversed(procdi)
TypeError: 'dict' object is not reversible
refreshing
page0
sda
sdb
/bin/sh: 1: nvidia-smi: not found
no nvidia gpu found
initialisating sidepane
page0
```

**Comment by KrispyCamel4u** [comment]
hi, thanks for this.
Can you let which python3 version you are using?

**Comment by KrispyCamel4u** [comment]
If you want a quick fix then you may replace content of one file.
Search where gproc.py is present in you file system in `/usr` dir. Mostly it will it will be in `/usr/lib/python3/dist-packages/sysmontask` or `/usr/local/lib/python3/dist-packages/sysmontask`. Then replace the content of gproc.py with the file given(gproc.txt) below. It should solve the issue.
Since new release might take some time because I m working on new features so for time being this will do the trick.
[gproc.txt](https://github.com/KrispyCamel4u/SysMonTask/files/6816172/gproc.txt)

Let me know if you face any problem.

**Comment by GokhanOfficial** [comment]
It fixed all of the problems. Thanks for support, nice work.

**Comment by Faq** [comment]
Now just need to release it.

**Comment by KrispyCamel4u** [comment]
New release is out with bug fix.
Let me know if it still persists.
