### ISSUE TITLE
app crashes on startup after hiding elements in resources view

### ISSUE THREAD

**Issue by HitLuca** [KrispyCamel4u/SysMonTask#81]
After removing a docker bridge in the connections view and restarting my pc, I am unable to start sysmontask anymore. By looking at the error it fails when trying to hide the docker bridge, and crashes when it's not there. I tried looking for the config file with the excluded elements, but I can't seem to find it.

To fix my issue I just need to find the config file, but maybe it would be better to add some error handling to it

**Comment by HitLuca** [comment]
Ok I at least was able to fix the issue on my side: I opened the `sysmontask.py` file, and added a `try-catch` in that block. I then opened and closed the program, which I guess updated the config entry. Removing the try-catch brought the project as it was but without startup crashes

**Comment by KrispyCamel4u** [comment]
Hi can you explain a bit more about your setup and how you are running it.
Are you running inside the docker?

**Comment by HitLuca** [comment]
Sure,
I am running sysmontask on a standard ubuntu desktop machine. I also have a docker project running, and since I have port mappings in it, docker automatically creates virtual adapters when it starts up. I had sysmontask when the project was running, and didn't care about the adapter so I hid it. 
The second time I ran sysmontask I had the docker project stopped, which also removed the virtual adapter. This crashed sysmontask every time I tried to start it up since it couldn't find the entry to disable I guess. Restarting the docker project creates a new virtual adapter with a different name, so having it running didn't allow me to see the gui

**Comment by HitLuca** [comment]
I have the suspicion that It can be a more troubling issue, since hiding something like an external HDD and then removing it could crash the project in the same way

**Comment by KrispyCamel4u** [comment]
Thanks, I have got some idea, may be to identify the issue in more depth can try running sysmontask via terminal and do the same with you docker project and the output log would be usefull which gets printing on terminal in both the cases(log for each run)?

**Comment by HitLuca** [comment]
first run, an usb stick in `/sdc` is inserted
```
5.8.0
color prifile in the setting {'cpu': (0.384, 0.749, 1.0), 'memory': (0.627, 0.196, 0.788), 'disk': (0.109, 0.67, 0.0588), 'network': (0.709, 0.164, 0.164), 'gpu': (0.384, 0.749, 1.0)}
cpuInit
Memory Tab Initialising
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
Failed to get Memory Form Factor
sda
sdb
sdc
nvme1n1
nvme0n1
nvme2n1
nvme3n1
WARNING: you should run this program as super-user.
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
okk
save button
update Dir right True
update speed to normal
device {'cpu': 0, 'memory': 1, 'sda': 2, 'sdb': 3, 'sdc': 4, 'nvme1n1': 5, 'nvme0n1': 6, 'nvme2n1': 7, 'nvme3n1': 8, 'enp4s0': 9, 'wlp5s0': 10, 'br-2d145d717ec4': 11, 'veth058a4a3': 12, 'GeForce RTX 2070': 13}
initialisating sidepane
total window 2.7884960174560547
appending 1478
[...]
appending 24020
poping 23825
poping 23798
poping 23804
print with cancel
```
starting it again and hiding `sdc`
```
5.8.0
color prifile in the setting {'cpu': (0.384, 0.749, 1.0), 'memory': (0.627, 0.196, 0.788), 'disk': (0.109, 0.67, 0.0588), 'network': (0.709, 0.164, 0.164), 'gpu': (0.384, 0.749, 1.0)}
cpuInit
Memory Tab Initialising
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
Failed to get Memory Form Factor
sda
sdb
sdc
nvme1n1
nvme0n1
nvme2n1
nvme3n1
WARNING: you should run this program as super-user.
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
okk
save button
update Dir right True
update speed to normal
device {'cpu': 0, 'memory': 1, 'sda': 2, 'sdb': 3, 'sdc': 4, 'nvme1n1': 5, 'nvme0n1': 6, 'nvme2n1': 7, 'nvme3n1': 8, 'enp4s0': 9, 'wlp5s0': 10, 'br-2d145d717ec4': 11, 'veth058a4a3': 12, 'GeForce RTX 2070': 13}
initialisating sidepane
total window 2.3683297634124756
appending 1478
[...]
appending 24114
[4] <------------------ when I hid sdc this printed
print with cancel
```
removing sdc and restarting it
```
5.8.0
color prifile in the setting {'cpu': (0.384, 0.749, 1.0), 'memory': (0.627, 0.196, 0.788), 'disk': (0.109, 0.67, 0.0588), 'network': (0.709, 0.164, 0.164), 'gpu': (0.384, 0.749, 1.0)}
cpuInit
Memory Tab Initialising
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
Failed to get Memory Form Factor
sda
sdb
nvme1n1
nvme0n1
nvme2n1
nvme3n1
WARNING: you should run this program as super-user.
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
okk
save button
update Dir right True
update speed to normal
device {'cpu': 0, 'memory': 1, 'sda': 2, 'sdb': 3, 'nvme1n1': 4, 'nvme0n1': 5, 'nvme2n1': 6, 'nvme3n1': 7, 'enp4s0': 8, 'wlp5s0': 9, 'br-2d145d717ec4': 10, 'veth058a4a3': 11, 'GeForce RTX 2070': 12}
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 11, in <module>
    load_entry_point('sysmontask===1.x.x', 'console_scripts', 'sysmontask')()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 1127, in start
    main=myclass()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 247, in __init__
    self.post_init()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 301, in post_init
    self.hidden_stack_page_numbers.append(self.device_stack_page_lookup[i])
KeyError: 'sdc'
```
reinserting the usb, and setting `sdc` back to visible
```
5.8.0
color prifile in the setting {'cpu': (0.384, 0.749, 1.0), 'memory': (0.627, 0.196, 0.788), 'disk': (0.109, 0.67, 0.0588), 'network': (0.709, 0.164, 0.164), 'gpu': (0.384, 0.749, 1.0)}
cpuInit
Memory Tab Initialising
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
Failed to get Memory Form Factor
sda
sdb
sdc
nvme1n1
nvme0n1
nvme2n1
nvme3n1
WARNING: you should run this program as super-user.
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
okk
save button
update Dir right True
update speed to normal
device {'cpu': 0, 'memory': 1, 'sda': 2, 'sdb': 3, 'sdc': 4, 'nvme1n1': 5, 'nvme0n1': 6, 'nvme2n1': 7, 'nvme3n1': 8, 'enp4s0': 9, 'wlp5s0': 10, 'br-2d145d717ec4': 11, 'veth058a4a3': 12, 'GeForce RTX 2070': 13}
initialisating sidepane
total window 2.2764270305633545
appending 1478
[...]
appending 24470
poping 24376
poping 24375
poping 24354
poping 24350
[] <------------------ when I re-showed sdc this printed
print with cancel
```

**Comment by Nrew-github** [comment]
~$ sysmontask
5.9.4
color prifile in the setting {'cpu': (0.384, 0.749, 1.0), 'memory': (0.627, 0.196, 0.788), 'disk': (0.109, 0.67, 0.0588), 'network': (0.709, 0.164, 0.164), 'gpu': (0.384, 0.749, 1.0)}
cpuInit
Failed to get Cache information
Memory Tab Initialising
/bin/sh: 1: dmidecode: not found
/bin/sh: 1: dmidecode: not found
Failed to get Memory Form Factor
sda
sdb
sdc
/bin/sh: 1: lshw: not found
lshw not found
Error in getting Product/Vendor cannot access local variable 'netinfo' where it is not associated with a value                           
okk                                                                                                                                      
save button                                                                                                                              
update Dir right True                                                                                                                    
update speed to normal                                                                                                                   
device {'cpu': 0, 'memory': 1, 'sda': 2, 'sdb': 3, 'sdc': 4, 'enp3s0': 5, 'NVIDIA GeForce GT 740': 6}                                    
Traceback (most recent call last):                                                                                                       
  File "/usr/bin/sysmontask", line 33, in <module>                                                                                       
    sys.exit(load_entry_point('sysmontask===1.x.x', 'console_scripts', 'sysmontask')())                                                  
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                   
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 1127, in start                                                    
    main=myclass()                                                                                                                       
         ^^^^^^^^^                                                                                                                       
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 247, in __init__                                                  
    self.post_init()                                                                                                                     
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 301, in post_init
    self.hidden_stack_page_numbers.append(self.device_stack_page_lookup[i])
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 'sdd'

**Comment by Nrew-github** [comment]
sudo sysmontask
5.9.4
color prifile in the setting {'cpu': (0.384, 0.749, 1.0), 'memory': (0.627, 0.196, 0.788), 'disk': (0.109, 0.67, 0.0588), 'network': (0.709, 0.164, 0.164), 'gpu': (0.384, 0.749, 1.0)}
cpuInit
Failed to get Cache information
Memory Tab Initialising
sda
sdb
sdc
/bin/sh: 1: lshw: not found
lshw not found
Error in getting Product/Vendor cannot access local variable 'netinfo' where it is not associated with a value
okk
save button

(sysmontask:43273): dconf-WARNING **: 23:20:57.302: failed to commit changes to dconf: Не удалось выполнить дочерний процесс "dbus-launch" (Нет такого файла или каталога)
update Dir right True
update speed to normal
device {'cpu': 0, 'memory': 1, 'sda': 2, 'sdb': 3, 'sdc': 4, 'enp3s0': 5, 'NVIDIA GeForce GT 740': 6}
initialisating sidepane
total window 2.021177053451538
appending 2991

Worked!
