### ISSUE TITLE
instant crash on fedora 35 KDE

### ISSUE THREAD

**Issue by ninchuka** [KrispyCamel4u/SysMonTask#99]
```
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask==1.3.9', 'console_scripts', 'sysmontask')())
  File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/sysmontask/sysmontask.py", line 5, in <module>
    require_version("Wnck", "3.0")
  File "/usr/lib64/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Wnck not available

```
is what I get if I try to run it via terminal

**Comment by KrispyCamel4u** [comment]
Hi,
The wnck library is missing, please install with:
`sudo apt install gir1.2-wnck-3.0`
OR with your OS-specific(probably dnf/yum) package manager.

**Comment by ninchuka** [comment]
had to install libwnck3 on fedora which got it working ty
